# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/miranus/shy/cmake-3.2/bin/cmake

# The command to remove a file.
RM = /Users/miranus/shy/cmake-3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/miranus/work/Devs/miscible_mixing_series/miscible_mixing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/miranus/work/Devs/miscible_mixing_series/miscible_mixing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/miranus/shy/cmake-3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/miranus/shy/cmake-3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/miranus/work/Devs/miscible_mixing_series/miscible_mixing/CMakeFiles /Users/miranus/work/Devs/miscible_mixing_series/miscible_mixing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/miranus/work/Devs/miscible_mixing_series/miscible_mixing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ../test/mismix_p4est

# Build rule for target.
../test/mismix_p4est: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ../test/mismix_p4est
.PHONY : ../test/mismix_p4est

# fast build rule for target.
../test/mismix_p4est/fast:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/build
.PHONY : ../test/mismix_p4est/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named info

# Build rule for target.
info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 info
.PHONY : info

# fast build rule for target.
info/fast:
	$(MAKE) -f CMakeFiles/info.dir/build.make CMakeFiles/info.dir/build
.PHONY : info/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named runclean

# Build rule for target.
runclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runclean
.PHONY : runclean

# fast build rule for target.
runclean/fast:
	$(MAKE) -f CMakeFiles/runclean.dir/build.make CMakeFiles/runclean.dir/build
.PHONY : runclean/fast

#=============================================================================
# Target rules for targets named sign

# Build rule for target.
sign: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sign
.PHONY : sign

# fast build rule for target.
sign/fast:
	$(MAKE) -f CMakeFiles/sign.dir/build.make CMakeFiles/sign.dir/build
.PHONY : sign/fast

#=============================================================================
# Target rules for targets named strip_comments

# Build rule for target.
strip_comments: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strip_comments
.PHONY : strip_comments

# fast build rule for target.
strip_comments/fast:
	$(MAKE) -f CMakeFiles/strip_comments.dir/build.make CMakeFiles/strip_comments.dir/build
.PHONY : strip_comments/fast

source/amr/amr.o: source/amr/amr.cc.o
.PHONY : source/amr/amr.o

# target to build an object file
source/amr/amr.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/amr/amr.cc.o
.PHONY : source/amr/amr.cc.o

source/amr/amr.i: source/amr/amr.cc.i
.PHONY : source/amr/amr.i

# target to preprocess a source file
source/amr/amr.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/amr/amr.cc.i
.PHONY : source/amr/amr.cc.i

source/amr/amr.s: source/amr/amr.cc.s
.PHONY : source/amr/amr.s

# target to generate assembly for a file
source/amr/amr.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/amr/amr.cc.s
.PHONY : source/amr/amr.cc.s

source/constitutive_model/consti_model.o: source/constitutive_model/consti_model.cc.o
.PHONY : source/constitutive_model/consti_model.o

# target to build an object file
source/constitutive_model/consti_model.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/constitutive_model/consti_model.cc.o
.PHONY : source/constitutive_model/consti_model.cc.o

source/constitutive_model/consti_model.i: source/constitutive_model/consti_model.cc.i
.PHONY : source/constitutive_model/consti_model.i

# target to preprocess a source file
source/constitutive_model/consti_model.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/constitutive_model/consti_model.cc.i
.PHONY : source/constitutive_model/consti_model.cc.i

source/constitutive_model/consti_model.s: source/constitutive_model/consti_model.cc.s
.PHONY : source/constitutive_model/consti_model.s

# target to generate assembly for a file
source/constitutive_model/consti_model.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/constitutive_model/consti_model.cc.s
.PHONY : source/constitutive_model/consti_model.cc.s

source/main/main.o: source/main/main.cc.o
.PHONY : source/main/main.o

# target to build an object file
source/main/main.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/main/main.cc.o
.PHONY : source/main/main.cc.o

source/main/main.i: source/main/main.cc.i
.PHONY : source/main/main.i

# target to preprocess a source file
source/main/main.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/main/main.cc.i
.PHONY : source/main/main.cc.i

source/main/main.s: source/main/main.cc.s
.PHONY : source/main/main.s

# target to generate assembly for a file
source/main/main.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/main/main.cc.s
.PHONY : source/main/main.cc.s

source/main/run.o: source/main/run.cc.o
.PHONY : source/main/run.o

# target to build an object file
source/main/run.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/main/run.cc.o
.PHONY : source/main/run.cc.o

source/main/run.i: source/main/run.cc.i
.PHONY : source/main/run.i

# target to preprocess a source file
source/main/run.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/main/run.cc.i
.PHONY : source/main/run.cc.i

source/main/run.s: source/main/run.cc.s
.PHONY : source/main/run.s

# target to generate assembly for a file
source/main/run.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/main/run.cc.s
.PHONY : source/main/run.cc.s

source/particle/generator.o: source/particle/generator.cc.o
.PHONY : source/particle/generator.o

# target to build an object file
source/particle/generator.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/generator.cc.o
.PHONY : source/particle/generator.cc.o

source/particle/generator.i: source/particle/generator.cc.i
.PHONY : source/particle/generator.i

# target to preprocess a source file
source/particle/generator.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/generator.cc.i
.PHONY : source/particle/generator.cc.i

source/particle/generator.s: source/particle/generator.cc.s
.PHONY : source/particle/generator.s

# target to generate assembly for a file
source/particle/generator.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/generator.cc.s
.PHONY : source/particle/generator.cc.s

source/particle/integrator.o: source/particle/integrator.cc.o
.PHONY : source/particle/integrator.o

# target to build an object file
source/particle/integrator.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/integrator.cc.o
.PHONY : source/particle/integrator.cc.o

source/particle/integrator.i: source/particle/integrator.cc.i
.PHONY : source/particle/integrator.i

# target to preprocess a source file
source/particle/integrator.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/integrator.cc.i
.PHONY : source/particle/integrator.cc.i

source/particle/integrator.s: source/particle/integrator.cc.s
.PHONY : source/particle/integrator.s

# target to generate assembly for a file
source/particle/integrator.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/integrator.cc.s
.PHONY : source/particle/integrator.cc.s

source/particle/output.o: source/particle/output.cc.o
.PHONY : source/particle/output.o

# target to build an object file
source/particle/output.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/output.cc.o
.PHONY : source/particle/output.cc.o

source/particle/output.i: source/particle/output.cc.i
.PHONY : source/particle/output.i

# target to preprocess a source file
source/particle/output.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/output.cc.i
.PHONY : source/particle/output.cc.i

source/particle/output.s: source/particle/output.cc.s
.PHONY : source/particle/output.s

# target to generate assembly for a file
source/particle/output.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/output.cc.s
.PHONY : source/particle/output.cc.s

source/particle/particle.o: source/particle/particle.cc.o
.PHONY : source/particle/particle.o

# target to build an object file
source/particle/particle.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/particle.cc.o
.PHONY : source/particle/particle.cc.o

source/particle/particle.i: source/particle/particle.cc.i
.PHONY : source/particle/particle.i

# target to preprocess a source file
source/particle/particle.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/particle.cc.i
.PHONY : source/particle/particle.cc.i

source/particle/particle.s: source/particle/particle.cc.s
.PHONY : source/particle/particle.s

# target to generate assembly for a file
source/particle/particle.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/particle/particle.cc.s
.PHONY : source/particle/particle.cc.s

source/post_process/extract_data.o: source/post_process/extract_data.cc.o
.PHONY : source/post_process/extract_data.o

# target to build an object file
source/post_process/extract_data.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/post_process/extract_data.cc.o
.PHONY : source/post_process/extract_data.cc.o

source/post_process/extract_data.i: source/post_process/extract_data.cc.i
.PHONY : source/post_process/extract_data.i

# target to preprocess a source file
source/post_process/extract_data.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/post_process/extract_data.cc.i
.PHONY : source/post_process/extract_data.cc.i

source/post_process/extract_data.s: source/post_process/extract_data.cc.s
.PHONY : source/post_process/extract_data.s

# target to generate assembly for a file
source/post_process/extract_data.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/post_process/extract_data.cc.s
.PHONY : source/post_process/extract_data.cc.s

source/post_process/post_processing.o: source/post_process/post_processing.cc.o
.PHONY : source/post_process/post_processing.o

# target to build an object file
source/post_process/post_processing.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/post_process/post_processing.cc.o
.PHONY : source/post_process/post_processing.cc.o

source/post_process/post_processing.i: source/post_process/post_processing.cc.i
.PHONY : source/post_process/post_processing.i

# target to preprocess a source file
source/post_process/post_processing.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/post_process/post_processing.cc.i
.PHONY : source/post_process/post_processing.cc.i

source/post_process/post_processing.s: source/post_process/post_processing.cc.s
.PHONY : source/post_process/post_processing.s

# target to generate assembly for a file
source/post_process/post_processing.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/post_process/post_processing.cc.s
.PHONY : source/post_process/post_processing.cc.s

source/pre_process/constructor.o: source/pre_process/constructor.cc.o
.PHONY : source/pre_process/constructor.o

# target to build an object file
source/pre_process/constructor.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/constructor.cc.o
.PHONY : source/pre_process/constructor.cc.o

source/pre_process/constructor.i: source/pre_process/constructor.cc.i
.PHONY : source/pre_process/constructor.i

# target to preprocess a source file
source/pre_process/constructor.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/constructor.cc.i
.PHONY : source/pre_process/constructor.cc.i

source/pre_process/constructor.s: source/pre_process/constructor.cc.s
.PHONY : source/pre_process/constructor.s

# target to generate assembly for a file
source/pre_process/constructor.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/constructor.cc.s
.PHONY : source/pre_process/constructor.cc.s

source/pre_process/mesh_in.o: source/pre_process/mesh_in.cc.o
.PHONY : source/pre_process/mesh_in.o

# target to build an object file
source/pre_process/mesh_in.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/mesh_in.cc.o
.PHONY : source/pre_process/mesh_in.cc.o

source/pre_process/mesh_in.i: source/pre_process/mesh_in.cc.i
.PHONY : source/pre_process/mesh_in.i

# target to preprocess a source file
source/pre_process/mesh_in.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/mesh_in.cc.i
.PHONY : source/pre_process/mesh_in.cc.i

source/pre_process/mesh_in.s: source/pre_process/mesh_in.cc.s
.PHONY : source/pre_process/mesh_in.s

# target to generate assembly for a file
source/pre_process/mesh_in.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/mesh_in.cc.s
.PHONY : source/pre_process/mesh_in.cc.s

source/pre_process/read_and_write.o: source/pre_process/read_and_write.cc.o
.PHONY : source/pre_process/read_and_write.o

# target to build an object file
source/pre_process/read_and_write.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/read_and_write.cc.o
.PHONY : source/pre_process/read_and_write.cc.o

source/pre_process/read_and_write.i: source/pre_process/read_and_write.cc.i
.PHONY : source/pre_process/read_and_write.i

# target to preprocess a source file
source/pre_process/read_and_write.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/read_and_write.cc.i
.PHONY : source/pre_process/read_and_write.cc.i

source/pre_process/read_and_write.s: source/pre_process/read_and_write.cc.s
.PHONY : source/pre_process/read_and_write.s

# target to generate assembly for a file
source/pre_process/read_and_write.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/read_and_write.cc.s
.PHONY : source/pre_process/read_and_write.cc.s

source/pre_process/setup_dofs.o: source/pre_process/setup_dofs.cc.o
.PHONY : source/pre_process/setup_dofs.o

# target to build an object file
source/pre_process/setup_dofs.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/setup_dofs.cc.o
.PHONY : source/pre_process/setup_dofs.cc.o

source/pre_process/setup_dofs.i: source/pre_process/setup_dofs.cc.i
.PHONY : source/pre_process/setup_dofs.i

# target to preprocess a source file
source/pre_process/setup_dofs.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/setup_dofs.cc.i
.PHONY : source/pre_process/setup_dofs.cc.i

source/pre_process/setup_dofs.s: source/pre_process/setup_dofs.cc.s
.PHONY : source/pre_process/setup_dofs.s

# target to generate assembly for a file
source/pre_process/setup_dofs.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/pre_process/setup_dofs.cc.s
.PHONY : source/pre_process/setup_dofs.cc.s

source/solver/navier_stokes/control.o: source/solver/navier_stokes/control.cc.o
.PHONY : source/solver/navier_stokes/control.o

# target to build an object file
source/solver/navier_stokes/control.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/control.cc.o
.PHONY : source/solver/navier_stokes/control.cc.o

source/solver/navier_stokes/control.i: source/solver/navier_stokes/control.cc.i
.PHONY : source/solver/navier_stokes/control.i

# target to preprocess a source file
source/solver/navier_stokes/control.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/control.cc.i
.PHONY : source/solver/navier_stokes/control.cc.i

source/solver/navier_stokes/control.s: source/solver/navier_stokes/control.cc.s
.PHONY : source/solver/navier_stokes/control.s

# target to generate assembly for a file
source/solver/navier_stokes/control.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/control.cc.s
.PHONY : source/solver/navier_stokes/control.cc.s

source/solver/navier_stokes/projection_for_div_velocity.o: source/solver/navier_stokes/projection_for_div_velocity.cc.o
.PHONY : source/solver/navier_stokes/projection_for_div_velocity.o

# target to build an object file
source/solver/navier_stokes/projection_for_div_velocity.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/projection_for_div_velocity.cc.o
.PHONY : source/solver/navier_stokes/projection_for_div_velocity.cc.o

source/solver/navier_stokes/projection_for_div_velocity.i: source/solver/navier_stokes/projection_for_div_velocity.cc.i
.PHONY : source/solver/navier_stokes/projection_for_div_velocity.i

# target to preprocess a source file
source/solver/navier_stokes/projection_for_div_velocity.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/projection_for_div_velocity.cc.i
.PHONY : source/solver/navier_stokes/projection_for_div_velocity.cc.i

source/solver/navier_stokes/projection_for_div_velocity.s: source/solver/navier_stokes/projection_for_div_velocity.cc.s
.PHONY : source/solver/navier_stokes/projection_for_div_velocity.s

# target to generate assembly for a file
source/solver/navier_stokes/projection_for_div_velocity.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/projection_for_div_velocity.cc.s
.PHONY : source/solver/navier_stokes/projection_for_div_velocity.cc.s

source/solver/navier_stokes/solve_ns_equation.o: source/solver/navier_stokes/solve_ns_equation.cc.o
.PHONY : source/solver/navier_stokes/solve_ns_equation.o

# target to build an object file
source/solver/navier_stokes/solve_ns_equation.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/solve_ns_equation.cc.o
.PHONY : source/solver/navier_stokes/solve_ns_equation.cc.o

source/solver/navier_stokes/solve_ns_equation.i: source/solver/navier_stokes/solve_ns_equation.cc.i
.PHONY : source/solver/navier_stokes/solve_ns_equation.i

# target to preprocess a source file
source/solver/navier_stokes/solve_ns_equation.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/solve_ns_equation.cc.i
.PHONY : source/solver/navier_stokes/solve_ns_equation.cc.i

source/solver/navier_stokes/solve_ns_equation.s: source/solver/navier_stokes/solve_ns_equation.cc.s
.PHONY : source/solver/navier_stokes/solve_ns_equation.s

# target to generate assembly for a file
source/solver/navier_stokes/solve_ns_equation.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/navier_stokes/solve_ns_equation.cc.s
.PHONY : source/solver/navier_stokes/solve_ns_equation.cc.s

source/solver/phase/levelset.o: source/solver/phase/levelset.cc.o
.PHONY : source/solver/phase/levelset.o

# target to build an object file
source/solver/phase/levelset.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/phase/levelset.cc.o
.PHONY : source/solver/phase/levelset.cc.o

source/solver/phase/levelset.i: source/solver/phase/levelset.cc.i
.PHONY : source/solver/phase/levelset.i

# target to preprocess a source file
source/solver/phase/levelset.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/phase/levelset.cc.i
.PHONY : source/solver/phase/levelset.cc.i

source/solver/phase/levelset.s: source/solver/phase/levelset.cc.s
.PHONY : source/solver/phase/levelset.s

# target to generate assembly for a file
source/solver/phase/levelset.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/phase/levelset.cc.s
.PHONY : source/solver/phase/levelset.cc.s

source/solver/phase/solve_hyperbolic_equation.o: source/solver/phase/solve_hyperbolic_equation.cc.o
.PHONY : source/solver/phase/solve_hyperbolic_equation.o

# target to build an object file
source/solver/phase/solve_hyperbolic_equation.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/phase/solve_hyperbolic_equation.cc.o
.PHONY : source/solver/phase/solve_hyperbolic_equation.cc.o

source/solver/phase/solve_hyperbolic_equation.i: source/solver/phase/solve_hyperbolic_equation.cc.i
.PHONY : source/solver/phase/solve_hyperbolic_equation.i

# target to preprocess a source file
source/solver/phase/solve_hyperbolic_equation.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/phase/solve_hyperbolic_equation.cc.i
.PHONY : source/solver/phase/solve_hyperbolic_equation.cc.i

source/solver/phase/solve_hyperbolic_equation.s: source/solver/phase/solve_hyperbolic_equation.cc.s
.PHONY : source/solver/phase/solve_hyperbolic_equation.s

# target to generate assembly for a file
source/solver/phase/solve_hyperbolic_equation.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/solver/phase/solve_hyperbolic_equation.cc.s
.PHONY : source/solver/phase/solve_hyperbolic_equation.cc.s

source/support/utilities.o: source/support/utilities.cc.o
.PHONY : source/support/utilities.o

# target to build an object file
source/support/utilities.cc.o:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/support/utilities.cc.o
.PHONY : source/support/utilities.cc.o

source/support/utilities.i: source/support/utilities.cc.i
.PHONY : source/support/utilities.i

# target to preprocess a source file
source/support/utilities.cc.i:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/support/utilities.cc.i
.PHONY : source/support/utilities.cc.i

source/support/utilities.s: source/support/utilities.cc.s
.PHONY : source/support/utilities.s

# target to generate assembly for a file
source/support/utilities.cc.s:
	$(MAKE) -f CMakeFiles/../test/mismix_p4est.dir/build.make CMakeFiles/../test/mismix_p4est.dir/source/support/utilities.cc.s
.PHONY : source/support/utilities.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ../test/mismix_p4est"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... runclean"
	@echo "... sign"
	@echo "... strip_comments"
	@echo "... run"
	@echo "... info"
	@echo "... debug"
	@echo "... distclean"
	@echo "... release"
	@echo "... source/amr/amr.o"
	@echo "... source/amr/amr.i"
	@echo "... source/amr/amr.s"
	@echo "... source/constitutive_model/consti_model.o"
	@echo "... source/constitutive_model/consti_model.i"
	@echo "... source/constitutive_model/consti_model.s"
	@echo "... source/main/main.o"
	@echo "... source/main/main.i"
	@echo "... source/main/main.s"
	@echo "... source/main/run.o"
	@echo "... source/main/run.i"
	@echo "... source/main/run.s"
	@echo "... source/particle/generator.o"
	@echo "... source/particle/generator.i"
	@echo "... source/particle/generator.s"
	@echo "... source/particle/integrator.o"
	@echo "... source/particle/integrator.i"
	@echo "... source/particle/integrator.s"
	@echo "... source/particle/output.o"
	@echo "... source/particle/output.i"
	@echo "... source/particle/output.s"
	@echo "... source/particle/particle.o"
	@echo "... source/particle/particle.i"
	@echo "... source/particle/particle.s"
	@echo "... source/post_process/extract_data.o"
	@echo "... source/post_process/extract_data.i"
	@echo "... source/post_process/extract_data.s"
	@echo "... source/post_process/post_processing.o"
	@echo "... source/post_process/post_processing.i"
	@echo "... source/post_process/post_processing.s"
	@echo "... source/pre_process/constructor.o"
	@echo "... source/pre_process/constructor.i"
	@echo "... source/pre_process/constructor.s"
	@echo "... source/pre_process/mesh_in.o"
	@echo "... source/pre_process/mesh_in.i"
	@echo "... source/pre_process/mesh_in.s"
	@echo "... source/pre_process/read_and_write.o"
	@echo "... source/pre_process/read_and_write.i"
	@echo "... source/pre_process/read_and_write.s"
	@echo "... source/pre_process/setup_dofs.o"
	@echo "... source/pre_process/setup_dofs.i"
	@echo "... source/pre_process/setup_dofs.s"
	@echo "... source/solver/navier_stokes/control.o"
	@echo "... source/solver/navier_stokes/control.i"
	@echo "... source/solver/navier_stokes/control.s"
	@echo "... source/solver/navier_stokes/projection_for_div_velocity.o"
	@echo "... source/solver/navier_stokes/projection_for_div_velocity.i"
	@echo "... source/solver/navier_stokes/projection_for_div_velocity.s"
	@echo "... source/solver/navier_stokes/solve_ns_equation.o"
	@echo "... source/solver/navier_stokes/solve_ns_equation.i"
	@echo "... source/solver/navier_stokes/solve_ns_equation.s"
	@echo "... source/solver/phase/levelset.o"
	@echo "... source/solver/phase/levelset.i"
	@echo "... source/solver/phase/levelset.s"
	@echo "... source/solver/phase/solve_hyperbolic_equation.o"
	@echo "... source/solver/phase/solve_hyperbolic_equation.i"
	@echo "... source/solver/phase/solve_hyperbolic_equation.s"
	@echo "... source/support/utilities.o"
	@echo "... source/support/utilities.i"
	@echo "... source/support/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

